services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - ./app/${SCANNER_SETTINGS}:/data/app/${SCANNER_SETTINGS}
    env_file:
      - .env
    depends_on:
      - redis
      - selenium-hub
    networks:
      - default

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - default

  firefox:
    image: selenium/node-firefox:4.0.0-rc-1-prerelease-20210713
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - "7900:7900"

  selenium-hub:
    image: selenium/hub:4.0.0-rc-1-prerelease-20210713
    container_name: selenium-hub
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 300
      GRID_TIMEOUT: 300
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  worker:
    container_name: worker
    build:
      context: .
    volumes:
      - ./app/${SCANNER_SETTINGS}:/data/app/${SCANNER_SETTINGS}
    command: celery -A run.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - api
      - redis

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - redis